### ISSUE TITLE
improve readme setup documentation

### ISSUE THREAD

**Issue by Knorrke** [serlo/athene2#712]
before `composer.phar install` one also needs `sudo apt-get install php-curl`

Also, I can't build athene2 on windows directly with `docker-compose up --build -d`, failing with this error:

```
Building athene2
Traceback (most recent call last):
  File "site-packages\docker\utils\build.py", line 179, in create_archive
OSError: [Errno 22] Invalid argument: 'C:\\Users\\Benjamin\\workspace\\serlo\\athene2\\src\\vendor\\bin\\classmap_generator.php'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 127, in perform_command
  File "compose\cli\main.py", line 1052, in up
  File "compose\cli\main.py", line 1048, in up
  File "compose\project.py", line 466, in up
  File "compose\service.py", line 314, in ensure_image_exists
  File "compose\service.py", line 1027, in build
  File "site-packages\docker\api\build.py", line 154, in build
  File "site-packages\docker\utils\build.py", line 31, in tar
  File "site-packages\docker\utils\build.py", line 183, in create_archive
OSError: Can not read file in context: [userpath removed]\workspace\serlo\athene2\src\vendor\bin\classmap_generator.php
[16244] Failed to execute script docker-compose
```

what works for me is executing the following after docker-compose failed:

```
docker build -t athene2_athene2:latest .
``` 
(which gives the same missing file error but continues anyway). After that one can continue with `docker-compose up`

**Comment by inyono** [comment]
Underlying issue: probably symlinks created in subsystem (Ubuntu for Windows) that don't work correctly in the host

**Comment by Knorrke** [comment]
https://blogs.windows.com/buildingapps/2016/12/02/symlinks-windows-10/

**Comment by Knorrke** [comment]
superseded by https://github.com/serlo/serlo.org
